services:
  ai-service:
    build: ./apps/ai-service
    expose:
      - "50051:50051"
    volumes:
      - ./apps/ai-service:/app
    command: python
    restart: unless-stopped

  api:
    build: ./apps/api-server
    ports:
      - "8000:8000"   
    develop:
      watch:
        - action: sync+restart
          path: ./apps/api-server
          target: /app
          ignore: .venv/
        - action: rebuild
          path: ./apps/api-server/pyproject.toml
    command: uv run gunicorn src.app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq
      - minio

  worker:
    build: ./apps/worker
    depends_on:
      - ai-service
      - rabbitmq
      - postgres
    volumes:
      - ./apps/worker:/app
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    restart: unless-stopped

  frontend:
    build: ./apps/frontend
    ports:
      - "5173:517"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    command: bun run dev --host
    restart: unless-stopped
    depends_on:
      - api

  rabbitmq:
    image: rabbitmq:4.1.4-management
    ports:
      - "5672:5672"
      - "15672:1562"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  rabbitmq-data:
  postgres-data:
  minio-data: